### ISSUE TITLE
Can PVDegradationTools estimate the degradation for future plant performance without having the environmental chamber and module specific test data ?

### ISSUE THREAD

**Issue by saikatghosh90** [NREL/PVDegradationTools#16]
I want to predict the future degradation for an upcoming pv plant.

**Comment by martin-springer** [comment]
`PVDegradationTools` is still in early development. We provide a library of functions that focus on specific degradation mechanisms that can be applied to site specific environmental conditions. A holistic degradation analysis focusing on power degradation is not yet available.
