### ISSUE TITLE
Some errors in first few lines of codes. Pls help

### ISSUE THREAD

**Issue by saikatghosh90** [NREL/PVDegradationTools#17]
**Lines of code -** 
import os
import pandas as pd

import pvdeg 
from pvdeg import DATA_DIR

PSM_FILE = os.path.join(DATA_DIR,'psm3_demo.csv')

WEATHER, META = pvdeg.weather.read(PSM_FILE,'psm')

**Error-** 
Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\saikatghosh\degradation rates\degradation.py:11
    import pvdeg

  File ~\anaconda3\lib\site-packages\pvdeg\__init__.py:5
    from . import cli

  File ~\anaconda3\lib\site-packages\pvdeg\cli.py:1
    from pvdeg.standards import run_calc_standoff

  File ~\anaconda3\lib\site-packages\pvdeg\standards.py:18
    from . import weather

  File ~\anaconda3\lib\site-packages\pvdeg\weather.py:10
    from pvdeg import humidity

  File ~\anaconda3\lib\site-packages\pvdeg\humidity.py:7
    from numba import jit

  File ~\anaconda3\lib\site-packages\numba\__init__.py:55
    _ensure_critical_deps()

  File ~\anaconda3\lib\site-packages\numba\__init__.py:42 in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.24 or less")

ImportError: Numba needs NumPy 1.24 or less

**Comment by martin-springer** [comment]
We've made recent updates that should resolve the issues.
