### ISSUE TITLE
Program temperature.py for other temperature models

### ISSUE THREAD

**Issue by MDKempe** [NREL/PVDegradationTools#47]
Currently the temperature.py method will only run the sapm model. It should be able to run all of them.

**Comment by martin-springer** [comment]
Temperature models: https://pvlib-python.readthedocs.io/en/stable/reference/pv_modeling/temperature.html

**Comment by martin-springer** [comment]
temperature models we want to include:    [     if temp_model == "sapm":](https://github.com/NREL/PVDegradationTools/blob/46570d2605e5c3fb08058cb847dfc2db72e695d3/pvdeg/temperature.py#L50)

**Comment by tobin-ford** [comment]
Added a unified temperature function with pvlib temperature models. Live on dev_geospatial_scenario, complexity is a little higher than other pvlib function to allow for its use during scenario analysis but this should be abstracted with its implemenation into the scenario job pipeline.
