### ISSUE TITLE
Monte Carlo - Standoff.ipynb to break on merge 

### ISSUE THREAD

**Issue by tobin-ford** [NREL/PVDegradationTools#48]
Standoff tutorial notebook will break post merge, Kempe_Standoff -> main and dev_montecarlo -> main

**Comment by martin-springer** [comment]
@tobin-ford - merge either the `development` branch or `Kempe_standoff_PR` branch into your Monte Carlo branch. That should take care of this issue. 

You can do the merge in VSCode. Make sure you have your Monte Carlo branch checked out. Then got to `Source Control`, click on the three dots next to your branch name. In the dropdown menu go to `Branch` -> `Merge branch...` -> select one of the mentioned branches. This should take care of it.

**Comment by martin-springer** [comment]
if you get merge conflicts, you can look up how to resolve them here https://code.visualstudio.com/docs/sourcecontrol/overview
